@extends('layouts.app')

@section('title', 'Job opportunities')

@section('content')
<div class="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:py-14">
    <div class="flex flex-col justify-between gap-6 border-b border-line pb-8 sm:flex-row sm:items-end"><div><p class="eyebrow">Administration</p><h1 class="font-display mt-3 text-4xl sm:text-5xl">Job opportunities</h1></div><p class="text-sm text-muted"><span class="font-display text-3xl text-ink">{{ $publishedCount }}</span> published</p></div>
    <div class="mt-8 grid items-start gap-8 lg:grid-cols-[0.8fr_1.2fr]">
        <section class="border border-line bg-white p-5 sm:p-6"><p class="eyebrow">Recruiting</p><h2 class="font-display mt-2 text-2xl">Post a new role</h2><form method="POST" action="{{ route('admin.jobs.store') }}" class="mt-5 grid gap-5">@csrf<div class="field"><label for="title">Job title</label><input id="title" name="title" maxlength="180" value="{{ old('title') }}" required>@error('title')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field"><label for="company">Company</label><input id="company" name="company" maxlength="180" value="{{ old('company') }}" required>@error('company')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field"><label for="location">Location</label><input id="location" name="location" maxlength="180" value="{{ old('location') }}" required>@error('location')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field"><label for="employment_type">Employment type</label><input id="employment_type" name="employment_type" maxlength="80" value="{{ old('employment_type', 'Full-time') }}" required>@error('employment_type')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field"><label for="description">Description</label><textarea id="description" name="description" rows="6" maxlength="10000" required>{{ old('description') }}</textarea>@error('description')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field"><label for="requirements">Requirements <span class="font-normal text-muted">Optional</span></label><textarea id="requirements" name="requirements" rows="5" maxlength="10000">{{ old('requirements') }}</textarea>@error('requirements')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field"><label for="application_deadline">Application deadline <span class="font-normal text-muted">Optional</span></label><input id="application_deadline" name="application_deadline" type="date" min="{{ today()->toDateString() }}" value="{{ old('application_deadline') }}">@error('application_deadline')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field"><label for="status">Status</label><select id="status" name="status" required><option value="published" @selected(old('status', 'published') === 'published')>Publish now</option><option value="draft" @selected(old('status') === 'draft')>Save as draft</option></select></div><button type="submit" class="flex items-center justify-between bg-forest px-5 py-3.5 text-sm font-semibold text-white hover:bg-forest-dark"><span>Create job</span><span aria-hidden="true">&#8599;</span></button></form></section>
        <section class="min-w-0"><div class="mb-4 flex items-end justify-between gap-4"><h2 class="font-display text-2xl">All job postings</h2></div><div class="grid gap-3">@forelse ($jobs as $job)<article class="border border-line bg-white p-5 sm:p-6"><div class="flex flex-wrap items-start justify-between gap-3"><div><div class="flex flex-wrap items-center gap-2"><span class="text-xs font-semibold uppercase tracking-wider {{ $job->status === 'published' ? 'text-forest' : 'text-terracotta' }}">{{ ucfirst($job->status) }}</span><span class="text-xs text-muted">{{ $job->applications_count }} applications</span></div><h3 class="mt-2 break-words font-display text-2xl">{{ $job->title }}</h3><p class="mt-1 text-sm text-muted">{{ $job->company }} · {{ $job->location }}</p></div><span class="text-xs text-muted">{{ $job->creator?->username ?? 'Administrator' }}</span></div><div class="mt-5 flex flex-wrap items-center gap-4 border-t border-line pt-4"><a href="{{ route('admin.jobs.applications.index', $job) }}" class="text-sm font-semibold text-forest underline underline-offset-4">View applications</a><a href="{{ route('admin.jobs.edit', $job) }}" class="text-sm font-semibold text-forest underline underline-offset-4">Edit</a><form method="POST" action="{{ route('admin.jobs.update', $job) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $job->status === 'published' ? 'draft' : 'published' }}"><button type="submit" class="text-sm font-semibold text-forest underline underline-offset-4">{{ $job->status === 'published' ? 'Move to draft' : 'Publish' }}</button></form><form method="POST" action="{{ route('admin.jobs.destroy', $job) }}">@csrf @method('DELETE')<button type="submit" class="text-sm font-medium text-terracotta underline underline-offset-4">Delete</button></form></div></article>@empty<p class="border border-dashed border-line px-5 py-12 text-center text-sm text-muted">No job postings yet.</p>@endforelse</div><div class="mt-5">{{ $jobs->links() }}</div></section>
    </div>
</div>
@endsection